"""Add datetime field in Note

Revision ID: 7a7e65ae5eec
Revises: ba658c9fdc21
Create Date: 2024-08-29 23:25:06.279392

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a7e65ae5eec"
down_revision: Union[str, None] = "ba658c9fdc21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "note", sa.Column("create_date", sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("note", "create_date")
    # ### end Alembic commands ###
