"""Add user relationsheep to Note

Revision ID: ba658c9fdc21
Revises: 33ea026c9014
Create Date: 2024-08-29 07:23:21.073689

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ba658c9fdc21"
down_revision: Union[str, None] = "33ea026c9014"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "note", sa.Column("name", sa.String(length=128), nullable=False)
    )
    op.add_column("note", sa.Column("text", sa.String(), nullable=False))
    op.add_column("note", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "note", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "note", type_="foreignkey")
    op.drop_column("note", "user_id")
    op.drop_column("note", "text")
    op.drop_column("note", "name")
    # ### end Alembic commands ###
